
```{r setup, include=FALSE}
library(tidyverse)
library(sf) #Wrangling spatial data
install.packages("mapview")
library(mapview) #Quickly projecting map layers
```

## Importing the data
```{r}
all_lots <- read_sf("~/Desktop/Github/57th_FAR/raw_data/57th_street_lots.geojson")%>%
 # select(!("cb2010", "cd", "ownertype", "landmark")) %>%
  st_transform(4326) %>% 
  st_as_sf()

real_prop <- read_csv("~/Desktop/Github/57th_FAR/raw_data/real_property.csv") %>%
  filter(BLOCK > 900 & BLOCK < 1300 & AIR_RIGHTS == "Y")
# real_prop <- real_prop %>%
#   as.character(real_prop$LOT) %>%
#   rbind(str_pad(LOT, width = 4, side = c("Left"), pad = "0"))

  
glimpse(real_prop)
```

## Including Plots
```{r}
all_lots <- all_lots %>%
  mutate(maxfar = max(CommFAR, ResidFAR, FacilFAR),
         greaterfar = case_when(BuiltFAR > maxfar ~ 1,
                                BuiltFAR <= maxfar ~ 0),
         scalefar = case_when(BuiltFAR <= 3 ~ "3 or Less",
                              BuiltFAR > 3 & BuiltFAR <= 6 ~ "3-6",
                              BuiltFAR > 6 & BuiltFAR <= 9 ~ "6-9",
                              BuiltFAR > 9 & BuiltFAR <= 12 ~ "9-12",
                              BuiltFAR > 12 ~ "12+"),
         BLOCK = Block,
         LOT = Lot)

only_skyscrapers <-all_lots %>%
  filter(greaterfar == 1) 
mapview(only_skyscrapers)
```
```{r}
air_right_ <- real_prop %>%
  select(BLOCK, LOT) %>%
  group_by(BLOCK, LOT) %>%
  summarize(air_right_transf = n()) %>%
  ungroup()%>%
  right_join(all_lots, by = c("BLOCK", "LOT"))%>%
  filter(air_right_transf != 'NA')%>%
  st_as_sf()

mapview(air_right_)
```
```{r}
skyscraper_points <- read_sf("~/Desktop/Github/57th_FAR/raw_data/landmark_points.json")
  
```


```{r}
skyscraperbbl <- c( 1013307502, #252e57th
                    1011057501, # VIA57West
                    1010090029, #Senville Buildings
                    1013100001, #432 Park Ave
                    1011057501, #big tetrahedron building 
                    1010307501, #220 Central Park South
                    1010100025, #111 West 57th
                    1012720001, #Hemesphere House
                    1010107506, #One57
                    1010290027, #Osborne Apartment House
                    1011050029 #Helena 57 West **this might be wrong
                    )
skyscraper_lots <- all_lots %>%
  filter(BBL %in% skyscraperbbl)%>%
  st_as_sf()

mapview(all_lots)
```
# Writing geojson files
```{r}
sf::st_write(all_lots, "~/Desktop/Github/57th_FAR/data/skyscraper_lots.geojson", overwrite = TRUE, append = FALSE)
sf::st_write(skyscraper_lots, "~/Desktop/Github/57th_FAR/data/all_lots.geojson", overwrite = TRUE, append = FALSE)
```

